# Generated by Django 5.1.7 on 2025-03-22 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='category_task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=175)),
                ('description', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('star_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_shower', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.category_task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='category_task',
            index=models.Index(fields=['user'], name='task_catego_user_id_947d4b_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user'], name='task_task_user_id_7e78a9_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'category'], name='task_task_user_id_6e4709_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['star_date', 'end_date'], name='task_task_star_da_db61f1_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['is_shower'], name='task_task_is_show_e2e061_idx'),
        ),
    ]
